image: gitpod/workspace-full-vnc:latest
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - name: Start chrome
    command: sleep 3 && chromium --start-fullscreen --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' --hide-crash-restore-bubble https://docs.linuxserver.io &> /dev/null
  
  - name: Welcome
    command: sleep 5 && clear && echo "Hello Developer :D"
