image: gitpod/workspace-full-vnc:latest
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
tasks:
  - name: Start chrome
    command: sleep 3 && chromium --incognito --start-fullscreen --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' https://docs.linuxserver.io &> /dev/null
  
  - name: Welcome
    command: sleep 5 && clear && echo "Hello Developer :D"
    
  - command: sleep 10 && xdg-open "https://6080-$(hostname).ws-eu116.gitpod.io" & \
