image: gitpod/workspace-full:latest
    
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 6900
    onOpen: ignore
  - port: 6901
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 80
    onOpen: ignore

tasks:
  - name: Starting VNC
    init:  sh .gitpod.vnc.sh && exit

  - name: Welcome
    command: |
      echo "alias vnc='gp preview --external https://6901-$(hostname).ws-eu116.gitpod.io'" >> ~/.bashrc && \
      source ~/.bashrc && \
      clear && \
      echo "Hello Developer \(^o^)/" && \
      echo " "
    
# tasks:
#   - name: Create alias
#     command:  echo "alias vnc='xdg-open https://6080-$(hostname).ws-eu116.gitpod.io'" >> ~/.bashrc
  
#   - name: Start chrome
#     command: sleep 4 && chromium --incognito --start-fullscreen --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' https://gifdb.com/images/high/borat-very-nice-funny-forced-smile-hk994tn7eahm7yrk.webp
  
#   - name: Welcome message
#     command: sleep 5 && source ~/.bashrc && clear && echo "Hello Developer \(^o^)/" && echo " "

 # "openChrome": "xdg-open https://6080-$(hostname).ws-eu116.gitpod.io"
