image: gitpod/workspace-full-vnc:latest
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
tasks:   
  - name: Start chrome
    command: sleep 2 && chromium --incognito --start-fullscreen --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' https://docs.linuxserver.io &> /dev/null
  
  - name: Welcome message
    command: sleep 4 && clear && printf "Hello Developer \(^o^)/" && echo ""
