image: gitpod/workspace-full-vnc:latest
    
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
    
tasks:  
  - name: Start chrome
    command: sleep 2 && chromium --incognito --start-fullscreen --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' https://gifdb.com/images/high/borat-very-nice-funny-forced-smile-hk994tn7eahm7yrk.webp
  
  - name: Welcome message
    command: sleep 4 && clear && echo "Hello Developer \(^o^)/" && echo " "

 # "openChrome": "xdg-open https://6080-$(hostname).ws-eu116.gitpod.io"
