services:
  webtop:
    image: lscr.io/linuxserver/webtop:fedora-kde
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/docker/webtop/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"